/**
 * API Client for Family Photo Sharing
 *
 * Since we're using static export, all API calls go directly to AWS services
 * using presigned URLs generated by the Python upload script or Lambda functions.
 *
 * For the demo/prototype, data is stored in localStorage.
 * In production, you would add Lambda functions behind API Gateway.
 */

import { PhotoItem, AlbumItem, ShareLinkItem } from './types';

const CLOUDFRONT_URL = process.env.NEXT_PUBLIC_CLOUDFRONT_URL || '';

// In-memory demo data store (in production, this would be DynamoDB)
class DemoStore {
  private static ALBUMS_KEY = 'photo-share-albums';
  private static SHARE_LINKS_KEY = 'photo-share-links';

  static getAlbums(): AlbumItem[] {
    if (typeof window === 'undefined') return [];
    const stored = localStorage.getItem(this.ALBUMS_KEY);
    if (stored) {
      try {
        return JSON.parse(stored);
      } catch {
        return [];
      }
    }
    return [];
  }

  static saveAlbums(albums: AlbumItem[]): void {
    if (typeof window === 'undefined') return;
    localStorage.setItem(this.ALBUMS_KEY, JSON.stringify(albums));
  }

  static getAlbum(id: string): AlbumItem | null {
    const albums = this.getAlbums();
    return albums.find(a => a.id === id) || null;
  }

  static createAlbum(name: string, description?: string): AlbumItem {
    const albums = this.getAlbums();
    const newAlbum: AlbumItem = {
      id: `album-${Date.now()}-${Math.random().toString(36).substr(2, 6)}`,
      name,
      description,
      photoCount: 0,
      createdAt: new Date().toISOString(),
    };
    albums.push(newAlbum);
    this.saveAlbums(albums);
    return newAlbum;
  }

  static updateAlbum(id: string, updates: Partial<AlbumItem>): void {
    const albums = this.getAlbums();
    const index = albums.findIndex(a => a.id === id);
    if (index !== -1) {
      albums[index] = { ...albums[index], ...updates };
      this.saveAlbums(albums);
    }
  }

  static getPhotos(albumId: string): PhotoItem[] {
    if (typeof window === 'undefined') return [];
    const stored = localStorage.getItem(`photo-share-photos-${albumId}`);
    if (stored) {
      try {
        return JSON.parse(stored);
      } catch {
        return [];
      }
    }
    return [];
  }

  static savePhotos(albumId: string, photos: PhotoItem[]): void {
    if (typeof window === 'undefined') return;
    localStorage.setItem(`photo-share-photos-${albumId}`, JSON.stringify(photos));
    this.updateAlbum(albumId, { photoCount: photos.length });
  }

  static addPhoto(albumId: string, photo: PhotoItem): void {
    const photos = this.getPhotos(albumId);
    photos.push(photo);
    this.savePhotos(albumId, photos);
  }

  static getShareLinks(): Record<string, ShareLinkItem> {
    if (typeof window === 'undefined') return {};
    const stored = localStorage.getItem(this.SHARE_LINKS_KEY);
    if (stored) {
      try {
        return JSON.parse(stored);
      } catch {
        return {};
      }
    }
    return {};
  }

  static saveShareLink(link: ShareLinkItem): void {
    if (typeof window === 'undefined') return;
    const links = this.getShareLinks();
    links[link.token] = link;
    localStorage.setItem(this.SHARE_LINKS_KEY, JSON.stringify(links));
  }

  static getShareLink(token: string): ShareLinkItem | null {
    const links = this.getShareLinks();
    return links[token] || null;
  }
}

// API Client interface for future Lambda integration
export const apiClient = {
  albums: {
    list: async (): Promise<AlbumItem[]> => {
      return DemoStore.getAlbums();
    },

    get: async (id: string): Promise<AlbumItem | null> => {
      return DemoStore.getAlbum(id);
    },

    create: async (name: string, description?: string): Promise<AlbumItem> => {
      return DemoStore.createAlbum(name, description);
    },

    update: async (id: string, updates: Partial<AlbumItem>): Promise<void> => {
      DemoStore.updateAlbum(id, updates);
    },
  },

  photos: {
    list: async (albumId: string): Promise<PhotoItem[]> => {
      return DemoStore.getPhotos(albumId);
    },

    add: async (albumId: string, photo: PhotoItem): Promise<void> => {
      DemoStore.addPhoto(albumId, photo);
    },
  },

  share: {
    create: async (albumId: string, expiresInDays?: number): Promise<ShareLinkItem> => {
      const album = DemoStore.getAlbum(albumId);
      const token = `${Date.now().toString(36)}${Math.random().toString(36).substr(2, 10)}`;

      const link: ShareLinkItem = {
        token,
        albumId,
        albumName: album?.name || 'Unknown Album',
        url: `${window.location.origin}/share/${token}/`,
        createdAt: new Date().toISOString(),
        accessCount: 0,
      };

      if (expiresInDays) {
        const expiresAt = new Date();
        expiresAt.setDate(expiresAt.getDate() + expiresInDays);
        link.expiresAt = expiresAt.toISOString();
      }

      DemoStore.saveShareLink(link);
      return link;
    },

    get: async (token: string): Promise<ShareLinkItem | null> => {
      return DemoStore.getShareLink(token);
    },
  },

  upload: {
    getPresignedUrl: async (
      albumId: string,
      filename: string,
      contentType: string
    ): Promise<{ uploadUrl: string; photoKey: string; thumbnailKey: string }> => {
      // In production, this would call a Lambda function to generate presigned URLs
      // For demo, we return a mock response
      const photoId = `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
      const ext = filename.split('.').pop() || 'jpg';

      return {
        uploadUrl: `https://mock-presigned-url.s3.amazonaws.com/${photoId}.${ext}`,
        photoKey: `photos/demo/${albumId}/${photoId}.${ext}`,
        thumbnailKey: `thumbnails/demo/${albumId}/${photoId}_thumb.${ext}`,
      };
    },
  },
};

// Helper function to build image URLs
export function getImageUrl(key: string): string {
  if (CLOUDFRONT_URL) {
    return `${CLOUDFRONT_URL}/${key}`;
  }
  // Fallback to direct S3 URL
  return `https://yeshvant-photos-storage-2026.s3.us-east-1.amazonaws.com/${key}`;
}

export default apiClient;
